package com.faire.yawn.generators.property

import com.faire.yawn.YawnTableDef
import com.faire.yawn.util.ForeignKeyReference
import com.faire.yawn.util.YawnContext
import com.faire.yawn.util.YawnNamesGenerator.generateEmbeddedDefClassName
import com.google.devtools.ksp.symbol.KSType
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.ksp.toClassName

/**
 * Leverages the [YawnTableDef.EmbeddedDef] child generated by
 * [com.faire.yawn.generators.type.EmbeddedTypeGenerator] to create a field reference
 * for the embedded property.
 *
 * For example, given the following column:
 * ```
 *   @Embedded
 *   override lateinit var foo: Foo
 * ```
 *
 * It will look something like:
 * ```
 *  val foo: FooDef = FooDef()
 * ```
 *
 * This assumes that `FooDef` has been generated by the processor.
 * Note that `FooDef` extends [YawnTableDef.EmbeddedDef].
 */
internal object EmbeddedDefGenerator : YawnPropertyGenerator() {
  override val generatedType = YawnTableDef.EmbeddedDef::class

  override fun generate(
      yawnContext: YawnContext,
      fieldName: String, // in this example, `foo`
      fieldType: KSType, // in this example, `Foo`
      foreignKeyRef: ForeignKeyReference?, // always null
  ): PropertySpec {
    check(foreignKeyRef == null)

    // in this example, `FooDef`
    val typeName = yawnContext.newClassName
        .nestedClass(generateEmbeddedDefClassName(fieldType.toClassName()))

    // val foo: FooDef = FooDef()
    return PropertySpec.builder(fieldName, typeName)
        .initializer("%T()", typeName)
        .build()
  }
}
