name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up JDK
                uses: actions/setup-java@v4
                with:
                    java-version: 21
                    distribution: "temurin"

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4
                with:
                    gradle-home-cache-cleanup: true

            -   name: Check build configuration
                run: ./gradlew projects

            -   name: Assemble all modules
                run: ./gradlew assemble

            -   name: Run test, lint and checks
                run: ./gradlew check

            -   name: Generate documentation
                run: ./gradlew dokkaHtml

            -   name: Generate test report
                uses: dorny/test-reporter@v1
                if: success() || failure()
                with:
                    name: Test Results
                    path: "**/build/test-results/test/*.xml"
                    reporter: java-junit
                    fail-on-error: true
