name: Publish 

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest 

        steps:
            - name: Checkout code 
              uses: actions/checkout@v4

            - name: Set up JDK 
              uses: actions/setup-java@v4
              with:
                java-version: 21
                distribution: "temurin"

            - name: Setup Gradle 
              uses: gradle/actions/setup-gradle@v4
              with:
                gradle-home-cache-cleanup: true 

            - name: Verify build
              run: ./gradlew check

            - name: Extract version from tag
              id: extract_version
              run: |
                  echo "VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

            - name: Verify gradle.properties
              run: |
                VERSION='${{ steps.extract_version.outputs.VERSION }}'
                if [ -f gradle.properties ]; then
                    FILE_VERSION=$(grep -E '^version=' gradle.properties | cut -d= -f2)
                    if [ "$FILE_VERSION" != "$VERSION" ]; then
                        echo "::error::gradle.properties version ($FILE_VERSION) != tag version ($VERSION)"
                        exit 1
                    fi
                fi

            - name: Publish the artifacts
              env:
                  ORG_GRADLE_PROJECT_version: ${{ steps.extract_version.outputs.VERSION }}
                  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_USERNAME }}
                  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_PASSWORD }}
                  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
                  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY_PASSWORD }}
              run: |
                  ./gradlew publishAndReleaseToMavenCentral --no-parallel --no-configuration-cache

