# See https://github.com/amannn/action-semantic-pull-request
name: title-validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  title-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          subjectPattern: ^[^a-z].+$
          subjectPatternError: |
            The subject of the PR can't begin with a lowercase letter.
